INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('1', 'MoonLady', 'April 30th', 'So excited for the new season of #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('2', 'FaeNews', 'April 30th', 'RUMOR ALERT! I heard from a reliable source that the infamous Tamsin Thickey will be appearing in #TheHunt this year!');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('3', 'MoonLady', 'May 1st', 'AND WE’RE OFF! Got all my girlies over for the day 1 watch party! @LeaLea @HeartLes @RoraBorealis #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('4', 'DreadLordMike', 'May 1st', 'FIRST KILL! Dumbass orc didn’t stand a chance lmao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('5', 'LadiesMan22', 'May 1st', 'Tamsin can get it man i dont care how many people shes killed she can kill me if she wants #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('6', 'HeartLes', 'May 1st', 'uh oh that’s a lot of dogs╭(* _ *)╮this guy means business #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('7', 'DreadLordMike', 'May 1st', 'THEY CONVINCED HIM TO LEAVE? HOW? This is fucking scripted it’s so obvious #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('8', 'Oioilio', 'May 1st', 'Is that a bag of holding? Hells yeah these guys are gonna win if they know the astral plane trick lol. Would the producers allow it though? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('9', 'MoonLady', 'May 2nd', 'Did something happen to the broadcast? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('10', 'BigChefBilly', 'May 2nd', 'Oh the broadcast is back, who the hell is this guy? Seems like a sick cunt haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('11', 'BigChefBilly', 'May 2nd', 'HFS I LOOKED IT UP AND THATS A CRIME BOSS! HIS MAFIA RUNS THE WHOLE MARKET DRISTRICT AND THE ENTIRE FISHING INDUSTRY ON THE COAST! WHAT IS HE DOING HERE?? IS HE A HUNTER OR A PRISONER?????? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('12', 'FaeNews', 'May 2nd', 'BREAKING NEWS! Don Flipcup, feared leader of the Flipcup Family is apparently present this year! It’s unknown if he’s a prisoner or a hunter though! I’ll post more as we learn more! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('13', 'MoonLady', 'May 2nd', 'Is it snowing?? That’s crazy! The weather effects are so realistic this year! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('14', 'DreadLordMike', 'May 2nd', 'Oh shit these chicks are hot #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('15', 'LadiesMan22', 'May 2nd', 'I wish Tamsin would whisper in my ear like that broooo im down colossal lmao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('16', 'MikiFan100', 'May 2nd', 'These guys in the town don’t stand a chance, Tamsin and Ares are gonna whack em #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('17', 'MikiFan100', 'May 2nd', 'Told ya #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('18', 'Oioilio', 'May 2nd', 'How did they not see that mimic? Ametur hour lol #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('19', 'TheRealZaz', 'May 2nd', 'Say, who’s that handsome red guy?（￢з￢）#TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('20', 'MoonLady', 'May 3rd', 'Invisibility cloak acquired! These guys are really lucky! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('21', 'FaeNews', 'May 3rd', 'Gwendolyn the infamous culprit of the ale district murders makes a brief appearance before meeting her untimely end at the hands of Tamsin and Ares! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('22', 'LeaLea', 'May 3rd', 'Did anyone see them take the poisoned ale just now? It cut away just as they were doing it Σ(-᷅_-᷄ ๑) #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('23', 'HeartLes', 'May 3rd', 'AAAAA THAT DRAGON IS SO CUTE OMG #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('24', 'RoraBorealis', 'May 3rd', 'His name is Sparkle stooooopppp omg im crying #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('25', 'BobsCrabShackMidway', 'May 3rd', 'Good thing the cameras have darkvision lol #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('26', 'KrisIsKool', 'May 3rd', 'Just got in trouble from posting from the work account oops lol #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('27', 'TreeHuggerMaggy', 'May 3rd', 'The glowing mushrooms are sooo pretty, I wonder if they’re real #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('28', 'DreadLordMike', 'May 3rd', 'Hope they die in the rapids #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('29', 'KKMingo', 'May 3rd', 'I’m so fucking scared of spiders #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('30', 'KKMingo', 'May 3rd', 'Like actually though would it have killed them to put a little “arachnophobia warning” banner at the bottom of the screen or something? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('31', 'MoonLady', 'May 3rd', 'Aw they helped that spider! I suppose that’s the least they could do after Tamsin burned their house (¬､¬) spiders are people too! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('32', 'KKMingo', 'May 3rd', 'So fucking glad that part is over #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('33', 'LadiesMan22', 'May 4th', 'Watchin #TheHunt from the waffle house rn lol');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('34', 'LadiesMan22', 'May 4th', 'WHAT HAPPENED WHEN DID TAMSINS CLOTHES GET WET WHY DIDNT ANYONE TELL ME #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('35', 'LadiesMan22', 'May 4th', 'Got a brother bricked up in da waffle house nooooo lmfao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('36', 'Tim', 'May 4th', 'Is this some kind of maze? I have no idea what’s going on. What is that music that’s playing? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('37', 'LeaLea', 'May 4th', 'Why are they yelling down the tunnels? What do they know that we don’t (☉_ ☉) #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('38', 'MoonLady', 'May 4th', 'OMG they figured it out already? How??? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('39', 'DreadLordMike', 'May 4th', 'Why does it keep showing these losers? Surely there are other prisoners doing more interesting things, right? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('40', 'LindseyPosts', 'May 4th', 'A mirror maze! This is confusing to watch haha theres just reflections everywhere. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('41', 'GreatGreenGary', 'May 4th', 'They’re still underground? Snore #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('42', 'LeaLea', 'May 4th', 'OMG They tricked that guy into drinking the poisoned ale?? I knew they were going to use it for something crazy! These guys are so much fun to watch. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('43', 'BigChefBilly', 'May 4th', 'I think that guy was another Flipcup dude? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('44', 'User555', 'May 4th', 'Are they gonna go down there? It sounds so scary!! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('45', 'DreadLordMike', 'May 4th', 'Slip and fall #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('46', 'KKMingo', 'May 4th', 'MORE BUGS ARE YOU KIDDING ME? I can’t watch anymore #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('47', 'Oioilio', 'May 5th', 'The secret to opening the tomb was a knock knock joke? That’s so fucking funny lmao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('48', 'Oioilio', 'May 5th', 'THAT’S A DEMILICH! These guys are toast lmao they had a good run #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('49', 'DreadLordMike', 'May 5th', 'BRO NO WAY THEY JUST PUSHED THEIR TEAMMATES INTO THE BAG WITH THE DEMILICH HAHA YOOOOOO #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('50', 'DreadLordMike', 'May 5th', 'I take back everything I said, Tamsin and Ares fuck super hard, I’m so in. #TheHunt #TamsinsTeam');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('51', 'IrateIrene', 'May 5th', 'I can’t believe they did that! My heart is broken ;_; #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('52', 'HeartLes', 'May 5th', 'I’m crying, I can’t believe my beautiful Ares would kill their friends like that #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('53', 'MoonLady', 'May 5th', 'NOOO! What?? Why did they do that?? I don’t understand! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('54', 'LeaLea', 'May 5th', 'I thought these guys were going to win but now I don’t want them to. I feel sick. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('55', 'JinBeBringsIt', 'May 5th', 'OMG that was out of nowhere haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('56', 'Oioilio', 'May 5th', 'Honestly the biggest bummer is that they lost their bag of holding lmao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('57', 'GreatGreenGary', 'May 5th', 'They’re STILL underground? Come on man every time I tune in nothing is happening #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('58', 'GreatGreenGary', 'May 5th', 'Ok apparently something crazy just happened and I just keep tuning in at bad parts lol my bad yall #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('59', 'GeoffWithAG', 'May 5th', 'A dungeon at the bottom of a dungeon? How big is this place?? This is crazy! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('60', 'LeaLea', 'May 5th', 'Watching them kill monsters should be exciting but I don’t feel anything right now. I just want it to show what other prisoners are up to. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('61', 'KrisIsKool', 'May 5th', 'Why are they being so sus about this little girl? She’s been here since the beginning, that’s too long for an illusion spell to last. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('62', 'HeartLes', 'May 5th', 'They’re leaving without helping that little girl? Tamsin and Ares are monsters. I hope they lose. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('63', 'IrateIrene', 'May 5th', 'Why are they just leaving her??? She’s cold and scared!! ;_; #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('64', 'RoraBorealis', 'May 5th', '#TheHunt sucks this year, everyone is being mean and crazy. I just want it to be over.');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('65', 'DreadLordMike', 'May 5th', 'Seeing a lot of bitching and moaning about the little girl. Did nobody think to ask why a little girl is in a death game in the first place? No, just taking shit at face value, fucking dumbasses. It’s obviously not really a little girl, it’s some kind of creature. Ares already figured it out. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('66', 'Oioilio', 'May 5th', 'Wtf, is the rain going upward? How are they doing that? This show is awesome man #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('67', 'GreatGreenGary', 'May 5th', 'Oh shit, the new outfits are dope #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('68', 'LadiesMan22', 'May 5th', 'TAMSIN MY LOVE YOU LOOK SO SEXY IN YOUR PINK ROBE AHHH #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('69', 'Somebuddy', 'May 5th', 'Yeah it was smart to shoo that guy away honestly he looked sketch lol #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('70', 'FaeNews', 'May 6th', 'BREAKING NEWS! Since the strange turn of events yesterday when Tamsin and Ares killed their teammates, I’ve received many DMs regarding allegations toward their former companions. It seems Tamsin and Ares knew something we didn’t, and perhaps did the right thing. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('71', 'MoonLady', 'May 6th', 'Did anyone see the post from @FaeNews this morning? I feel bad for reacting the way I did without knowing the full story. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('72', 'LeaLea', 'May 6th', 'I’m still upset about leaving the little girl behind but I’ll forgive what happened with the demilich. They’re on thin ice though. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('73', 'HeartLes', 'May 6th', 'I knew Ares wouldn’t do something that horrible without a good reason! I love you Ares! I’m sorry for doubting you! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('74', 'BigMoose', 'May 6th', 'BIG MOOSE! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('75', 'User87997', 'May 6th', 'Yo they’re about to walk into that trap that that weird guy set up on like the second day lol has he been waiting here the whole time? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('76', 'RoraBorealis', 'May 6th', 'Are those real zombies?! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('77', 'KrisIsKool', 'May 6th', 'Knew those zombies didn’t stand a chance, but I wonder if they’ll find the lady hiding upstairs? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('78', 'TeaTreeTanya', 'May 6th', 'Isn’t this the lady that got separated from the little girl like 2 days ago? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('79', 'BuckTime1', 'May 6th', 'Anyone else think corella is relly pretty? in like a id love to watch her raise our beautiful children together kinda way ya know #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('80', 'ArrowDarren', 'May 6th', 'No way they’re going underground again fuck me #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('81', 'BobsCrabShackMidway', 'May 6th', 'Come on down to Bob’s Crab Shack at Midway Marketplace for 50% bushels until we run out #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('82', 'MoonLady', 'May 6th', 'These fog maze puzzles are so confusing, I feel so stupid watching them :o #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('83', 'TheRealZaz', 'May 7th', 'Hey, there he is again! What’s cookin’ good lookin’? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('84', 'LeaLea', 'May 7th', 'Yay they’re going back for the girl!! I hope everything works out! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('85', 'RoraBorealis', 'May 7th', 'Nooo Tamsin! I know you’re mad about her tricking Corella but don’t hurt her! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('86', 'DreadLordMike', 'May 7th', 'Damn that bitch got an arm on her #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('87', 'LadiesMan22', 'May 7th', 'Broooo what i would give to get choked by Tamsin like that ong hahahaha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('88', 'OnumaOkiyo', 'May 7th', 'Oh word? The changeling is really cute? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('89', 'MoonLady', 'May 7th', 'Wait, Artemis and Ares know each other?? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('90', 'LeaLea', 'May 7th', 'I’m not crying you’re crying (;﹏;) I soooo wish I could see the memory they shared #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('91', 'RoraBorealis', 'May 7th', 'They’re siblings????? AAAAAAAA I’M SO HAPPY #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('92', 'JessRockseeker', 'May 7th', 'I would die for Ares <3 #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('93', 'Somebuddy', 'May 7th', 'Is anyone going to mention that it seems weird that Artemis is supposedly 35 but looks 18? Is she still hiding her appearance? I don’t trust her. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('94', 'MoonLady', 'May 7th', 'What’s up with the rainbow lightning? It looks pretty #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('95', 'AnnWithAPlan', 'May 7th', '@Ominis @SlytherinSebastian TURN ON THE TV! TAMSIN IS IN THE HUNT THIS YEAR! HOW DID WE NOT HEAR ABOUT THIS! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('96', 'SlytherinSebastian', 'May 7th', '@AnnWithAPlan Honestly forgot I have an account on here. Didn\'t know Tamsin had turned to a life of crime after school, but I\'ll support her no matter what for what she did for us. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('97', 'SlytherinSebastian', 'May 7th', '@Ominis Come over to my place, I just thought of a great idea. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('98', 'DreadLordMike', 'May 7th', 'If they have one more fucking musical number I’m gonna kill myself #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('99', 'IrateIrene', 'May 7th', 'Tamsin is such a good dancer omg #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('100', 'SuperTailor', 'May 7th', 'How can they expect to reach the tower if they’re not going to use the boat? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('101', 'LeaLea', 'May 7th', 'THEY’RE WALKING ON WATER AAAA SO COOL #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('102', 'xXKnightOfDarknessXx', 'May 8th', 'If Artemis is a changeling why doesn’t she make her tits bigger #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('103', 'User321312', 'May 8th', 'They dont stand a chance against that giant haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('104', 'MoonLady', 'May 8th', '(,,•o•,,) woah it’s so foggy! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('105', 'User321312', 'May 8th', 'Alright maybe now they stand a chance against that giant haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('106', 'DreadLordMike', 'May 8th', 'They convinced it to leave? Again? Booooo #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('107', 'DreadLordMike', 'May 8th', 'Oh shit he blasted the fuck out of that ship haha at least someone got killed *snore* #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('108', 'HeartLes', 'May 8th', 'I’m so glad they didn’t fight the giant, he didn’t seem like a bad guy! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('109', 'IrateIrene', 'May 8th', 'Awww Ares and Corella are so cute together <3 #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('110', 'RoraBorealis', 'May 8th', 'I hope they kiss hehe #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('111', 'FaeNews', 'May 8th', 'BREAKING NEWS! Ares and Corella’s heart-to-heart is interrupted by an ambush! Ares is on the brink of death! Tune in right now, don’t miss it! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('112', 'JessRockseeker', 'May 8th', 'ARES NOOOO!! FIGHT FIGHT WIN!!! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('113', 'Somebuddy', 'May 8th', 'The halfelf is about to bite it haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('114', 'DreadLordMike', 'May 8th', 'Damn Tamsin killed them in her sleep haha, Ares is literally useless. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('115', 'LadiesMan22', 'May 8th', 'Tamsin is so fucking hot brooooo she killed those guys without even waking up #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('116', 'LeaLea', 'May 8th', 'Tamsin saved Ares!!! I’m so happy!!!!! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('117', 'MoonLady', 'May 8th', 'I think it’s sweet that Artemis apologized to Tamsin for pretending to be a kid so that Corella would protect her. I think Artemis is a good person in a scary situation and I think I would have done the same if I were her. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('118', 'KrisIsKool', 'May 8th', 'Do Tamsin and Ares really think it’s a good idea to bring Artemis with them into this underwater dungeon? She doesn’t really know how to fight. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('119', 'GreatGreenGary', 'May 8th', 'I wish they could talk underwater, I want to know why Tamsin and Ares keep gesturing at Artemis and frowning and shrugging at each other. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('120', 'BigChefBilly', 'May 8th', 'Omg I think Artemis has a flipcup mafia tattoo on her back. Did anyone else see that?? I feel like this is gonna be a problem lol #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('121', 'LadiesMan22', 'May 8th', 'Just when I thought Tamsin couldnt get any hotter she picks up a golden trident lookin like a goddess my love #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('122', 'User32231', 'May 8th', 'Oh shit I know that growl from my marine biology class, there’s a giant eel in this room with them lol they’re dead #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('123', 'JessRockseeker', 'May 8th', 'DID ARTEMIS JUST DIE??? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('124', 'LeaLea', 'May 8th', 'ARTEMIS NOOOO!!! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('125', 'KrisIsKool', 'May 8th', 'I literally just said they shouldn’t have brought Artemis haha damn #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('126', 'RoraBorealis', 'May 8th', 'Thank gods they killed that thing but is Artemis going to be ok?? #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('127', 'DreadLordMike', 'May 8th', 'Aw man they revived Artemis. All she fucking does is whine lol I was hoping that was the end of her. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('128', 'MoonLady', 'May 8th', 'This treasure room is so pretty omg #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('129', 'FaeNews', 'May 8th', 'THIS JUST IN! Artemis is from a rival gang?? What will Tamsin and Ares make of this revelation? Tune in now! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('130', 'HeartLes', 'May 8th', 'Artemis is right, why does it matter if they were in gangs before? If they win they’ll be rich and famous, their old lives don’t matter anymore. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('131', 'Somebuddy', 'May 8th', 'Artemis said the pong family’s boss hasn’t done anything to help Ares and Tamsin but he literally sent that guy Sneaky Jimmy in to give them advice. I still don’t trust this bitch. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('132', 'LeaLea', 'May 8th', 'I feel so bad for Artemis. She didn’t ask for any of this. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('133', 'DreadLordMike', 'May 8th', 'More crocodile tears from Artemis, what else is new lmao #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('134', 'JamesIndrade', 'May 8th', 'I love that it keeps cutting to Corella just sitting on the surface of the sea and waiting lmao the editors have a good sense of humor #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('135', 'TeaTreeTanya', 'May 8th', 'Omg just when I was wondering what this kobold and tabaxi are arguing about the tabaxi blows the kobolds head off #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('136', 'FaeNews', 'May 8th', 'Don Flipcup makes another appearance to taunt Tamsin during her night shift! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('137', 'DreadLordMike', 'May 8th', 'Oh fuck she put the personality top hat on his head haha #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('138', 'BigChefBilly', 'May 8th', 'Of all the people the hat could have made the don think he was, it picked Ranrok? That’s insane. #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('139', 'FaeNews', 'May 8th', 'BREAKING NEWS! Ranrok, the infamous goblin warlord famously slain by Tamsin Thickey years ago has evidently escaped from his prison in The Nine Hells! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('140', 'RoraBorealis', 'May 8th', 'AAAA HE HAS THE HEAD OF THE HUNTER THAT HAD ALL THW WOLVES! THIS IS SO SCARY!! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('141', 'BuckTime1', 'May 9th', 'Oh fuck corella is so big got me feelin some kinda way #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('142', 'JessRockseeker', 'May 9th', 'AWWW SMOL ARES! I LOVE THEM SO MUCH! #TheHunt');
INSERT INTO GLYPH (glyph_id, username, glyph_date, glyph_content) VALUES ('143', 'KrisIsKool', 'May 9th', 'I keep seeing customers at work doing the mage hand dance that Tamsin does lol #TheHunt');